# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
reviews:
  profile: "chill"            # "chill", "balanced", "thorough", etc.
  request_changes_workflow: false
  high_level_summary: true
  review_status: true
  auto_review:
    enabled: true             # make sure PRs auto-review
    drafts: false             # don't review draft PRs
chat:
  auto_reply: true
